# Modules
- color: "fbca04"
  description: "This issue or pull request is related to cache-policy module."
  name: ":floppy_disk: cache-policy"
- color: "fbca04"
  description: "This issue or pull request is related to distribution module."
  name: ":floppy_disk: distribution"
- color: "fbca04"
  description: "This issue or pull request is related to key-value-store module."
  name: ":floppy_disk: key-value-store"
- color: "fbca04"
  description: "This issue or pull request is related to origin-access-control module."
  name: ":floppy_disk: origin-access-control"
- color: "fbca04"
  description: "This issue or pull request is related to origin-request-policy module."
  name: ":floppy_disk: origin-request-policy"
- color: "fbca04"
  description: "This issue or pull request is related to response-headers-policy module."
  name: ":floppy_disk: response-headers-policy"
- color: "fbca04"
  description: "This issue or pull request is related to vpc-origin module."
  name: ":floppy_disk: vpc-origin"
